/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLotsRouteImport } from './routes/_app.lots'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppProjetsIndexRouteImport } from './routes/_app.projets.index'
import { Route as AppProjetsIdRouteImport } from './routes/_app.projets.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLotsRoute = AppLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetsIndexRoute = AppProjetsIndexRouteImport.update({
  id: '/projets/',
  path: '/projets/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetsIdRoute = AppProjetsIdRouteImport.update({
  id: '/projets/$id',
  path: '/projets/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/lots': typeof AppLotsRoute
  '/projets/$id': typeof AppProjetsIdRoute
  '/projets/': typeof AppProjetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/lots': typeof AppLotsRoute
  '/projets/$id': typeof AppProjetsIdRoute
  '/projets': typeof AppProjetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lots': typeof AppLotsRoute
  '/_app/projets/$id': typeof AppProjetsIdRoute
  '/_app/projets/': typeof AppProjetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/lots' | '/projets/$id' | '/projets/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/lots' | '/projets/$id' | '/projets'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/lots'
    | '/_app/projets/$id'
    | '/_app/projets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lots': {
      id: '/_app/lots'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof AppLotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projets/': {
      id: '/_app/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof AppProjetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projets/$id': {
      id: '/_app/projets/$id'
      path: '/projets/$id'
      fullPath: '/projets/$id'
      preLoaderRoute: typeof AppProjetsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLotsRoute: typeof AppLotsRoute
  AppProjetsIdRoute: typeof AppProjetsIdRoute
  AppProjetsIndexRoute: typeof AppProjetsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLotsRoute: AppLotsRoute,
  AppProjetsIdRoute: AppProjetsIdRoute,
  AppProjetsIndexRoute: AppProjetsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
